import type { Metadata } from "next";
import "./globals.css";
import AppLayout from "@/layouts/AppLayout";
// import { AuthProvider } from "@/providers/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppLayout>
          <>{children}</>
        </AppLayout>
      </body>
    </html>
  );
}
